### ISSUE TITLE
Epic 4: Data Transformation Decisions

### ISSUE THREAD

**Issue by glind** [GMB-Interns/ETL#5]
User Story 1: As a user, I want to to decide how my data is transformed
Subtasks:

- [x] Implement authentication and authorization for accessing the ETL rules
- [ ] Prompt user in bash script to restore data to test from prod first, then run migrations and create new tables as needed for testing.
- [ ] Prompt user for dynamic table.columns to anonymize after asking if they would like to anonymize the data.
- [ ] Create a set of high level rules for the data including Anonymization (Yes/No), De-Duplication and Append or Reset
